# Generated by Django 5.1.5 on 2025-03-05 19:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='A short bio about the artist.', null=True)),
                ('profile_picture', models.ImageField(blank=True, help_text='Upload a profile picture.', null=True, upload_to='profiles/')),
                ('full_name', models.CharField(blank=True, help_text='Your display name (e.g., Peter Mwangi).', max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, help_text='Your contact phone number.', max_length=20, null=True)),
                ('email_public', models.EmailField(blank=True, help_text='A public email for inquiries (optional).', max_length=254, null=True)),
                ('location', models.CharField(blank=True, help_text='Where you’re based (e.g., Kibera, Nairobi).', max_length=100, null=True)),
                ('linkedin_url', models.URLField(blank=True, help_text='Your LinkedIn profile URL (optional).', null=True)),
                ('facebook_url', models.URLField(blank=True, help_text='Your Facebook profile or page URL (optional).', null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Your Instagram profile URL (optional).', null=True)),
                ('artistic_style', models.CharField(blank=True, choices=[('acrylic', 'Acrylic Painting'), ('oil', 'Oil Painting'), ('watercolor', 'Watercolor'), ('mixed_media', 'Mixed Media'), ('sculpture', 'Sculpture'), ('mural', 'Mural Art'), ('digital', 'Digital Art'), ('traditional', 'Traditional Craft'), ('other', 'Other')], help_text='Select your primary artistic style (optional).', max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the profile was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the profile was last updated.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artist Profile',
                'verbose_name_plural': 'Artist Profiles',
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the artwork.', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of the artwork.', null=True)),
                ('image', models.ImageField(help_text='Upload the artwork image.', upload_to='artworks/')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the artwork in KSH.', max_digits=10)),
                ('is_available', models.BooleanField(default=True, help_text='Is this artwork available for purchase?')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the artwork was uploaded.')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='prof.artistprofile')),
            ],
        ),
    ]
