# Generated by Django 5.1.5 on 2025-03-08 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0002_alter_artistprofile_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
