# Generated by Django 5.1.5 on 2025-03-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='merchant_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
