# Generated by Django 5.1.5 on 2025-03-12 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='guides/')),
                ('bio', models.TextField(blank=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('guided_city_walk', 'Guided City Walk'), ('cultural_heritage', 'Cultural & Heritage Tour'), ('street_food', 'Street Food Experience'), ('art_graffiti', 'Art & Graffiti Tour'), ('nightlife', 'Nightlife & Entertainment Tour')], max_length=100)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='featured/')),
                ('base_duration', models.CharField(choices=[('half_day', 'Half-Day'), ('full_day', 'Full-Day'), ('custom', 'Custom')], default='half_day', max_length=50)),
                ('estimated_start_time', models.TimeField(default='09:00:00')),
                ('estimated_end_time', models.TimeField(default='12:00:00')),
                ('price', models.DecimalField(decimal_places=2, default=1000.0, max_digits=10)),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tours.guide')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('is_booked', models.BooleanField(default=False)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='available_slots', to='tours.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_size', models.CharField(choices=[('single', 'Single'), ('couple', 'Couple'), ('group', 'Group')], default='single', max_length=20)),
                ('tour_duration', models.CharField(choices=[('half_day', 'Half-Day'), ('full_day', 'Full-Day'), ('custom', 'Custom')], default='half_day', max_length=50)),
                ('tour_type', models.CharField(choices=[('walking', 'Walking Tour'), ('boda_boda', 'Boda Boda (Motorbike)')], default='walking', max_length=20)),
                ('meeting_point', models.CharField(choices=[('sarangombe', 'Meeting at Sarang’ombe'), ('hotel_pickup', 'Hotel Pickup')], default='sarangombe', max_length=50)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.timeslot')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.tour')),
            ],
        ),
    ]
