# Generated by Django 5.1.5 on 2025-03-08 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_regularuserprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
    ]
